blank_issues_enabled: false
contact_links:
  - name: 📧 Contact School IT Support
    url: mailto:it-support@mergington.edu
    about: For urgent technical issues or system access problems, contact our IT support team directly.
  - name: 📚 Development Documentation
    url: https://github.com/riniepel-demo-org/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Technical documentation for developers working on this application.